### PR TITLE
[WIP] fixes #____ - use labels on create

### PR DESCRIPTION
**Pull request by thomasmckay**
Needs issue created and tests.
When label is specified in products and content-views, use that rather than labelizing name.

### CODE REVIEW

**Comment by akofink** [comment]
Any update here?

**Comment by thomasmckay** [comment]
@akofink - The tests I wrote don't work consistently (I think it's a timing of create then search too quickly). I probably won't return to this PR until January.

**Comment by beav** [comment]
@thomasmckay is this PR still WIP? Can the redmine issue be declassified? :sunglasses: :wink:

**Comment by akofink** [comment]
Closing for inactivity

**Pull request closed without merging**
