### PR TITLE
Fixes #17624 - Compatibility with authenticators

### PR DESCRIPTION
**Pull request by tstrachota**
- use existing foreman api connection for csv too
- adds compatibility with authenticators

### CODE REVIEW

**Comment by tstrachota** [comment]
@thomasmckay the tests are failing because travis.yml installs hammer-cli from source (master) but uses latest released hammer-cli-foreman that are incompatible at the moment.

Before I do any changes, what was the reason behind using master for the core, please?

**Comment by thomasmckay** [comment]
@tstrachota - I don't recall specifically but it was likely that the released hammer-cli was out of date for a long enough time that it was blocking work. Changing to use released would be fine, I think.

**Comment by akofink** [comment]
Alternatively, we could change travis.yml to run hammer-cli-foreman from master as well, right? I think this is what we do in hammer-cli-katello.

**Comment by thomasmckay** [comment]
personally i'd lean towards using master in travis.yml to 1) find inconsistencies sooner, 2) not be blocked on gem releases. thoughts?

**Comment by tstrachota** [comment]
If the assumption is that csv will always run on the latest release of `hammer-cli[-foreman\-katello]` then it probably makes sense to use upstream for the PR tests.
`.travis.yml`updated, I'm going to fix the tests now.

**Comment by tstrachota** [comment]
I found out the last failing test is caused by http://projects.theforeman.org/issues/17650 ...fixing now.

**Comment by tstrachota** [comment]
FYI https://github.com/theforeman/hammer-cli-foreman/pull/271

**Comment by thomasmckay** [comment]
My other PRs will return coveralls to green.

@akofink - ack w/ coveralls failure?

**Comment by akofink** [comment]
ACK from me

**Comment by thomasmckay** [comment]
ack - please squash before merge

**Pull request merged**
