### PR TITLE
fixes #17505, #17052 - refine search for subs in act-keys and content-hosts

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by akofink** [comment]
I'm still seeing the same result from #17052. The ak1 activation key starts with no subs attached in the example below.

```
$ cat aksi.csv 
Name,Organization,Description,Limit,Environment,Content View,Host Collections,Auto-Attach,Service Level,Release Version,Subscription Name,Subscription Type,Subscription Quantity,Subscription SKU,Subscription Contract,Subscription Account,Subscription Start,Subscription End,Subscription Guest
ak1,Default Organization,,,,Default Organization View,"",Yes,,,Employee SKU,Red Hat,1,ES0113909,10913844,1212729,2016-03-24T04:00:00+00:00,2022-01-01T04:59:59+00:00,
ak1,Default Organization,,,,Default Organization View,"",Yes,,,Employee SKU,Red Hat,1,ES0113909,10913844,1212729,2016-03-24T04:00:00+00:00,2022-01-01T04:59:59+00:00,akofink-desktop.usersys.redhat.com

$ hammer csv activation-keys --itemized-subscriptions --file aksi.csv -v
Updating subscriptions for activation key 'ak1'... attaching 1 of 'Employee SKU'...done
Updating subscriptions for activation key 'ak1'... 'Employee SKU' already attached...done
```

**Comment by thomasmckay** [comment]
@akofink - Corrected logic to not find incorrect matches for existing VDC subscription when trying to add guest subs to the act key. In general, this is not encouraged practice but the same situation would have prevented multiple guest subs from different hypervisors from being attached so great catch. Note that the csv file you used had the 'Subscription Type' for the guest sub as 'Red Hat' instead of 'Red Hat Guest' which would legitimately fail to find a matching sub.

**Comment by akofink** [comment]
@thomasmckay I just exported these subs with the updated code, and I'm still not seeing the 'Red Hat Guest' 'Subscription Type' in the CSV. It seems like this is unexpected behavior from your previous comment:

image

```sh
$ hammer csv activation-keys --itemized-subscriptions --export --file aksi.csv
$ cat aksi.csv 
Name,Organization,Description,Limit,Environment,Content View,Host Collections,Auto-Attach,Service Level,Release Version,Subscription Name,Subscription Type,Subscription Quantity,Subscription SKU,Subscription Contract,Subscription Account,Subscription Start,Subscription End,Subscription Guest
ak1,Default Organization,,,,Default Organization View,"",Yes,,,Employee SKU,Red Hat,1,ES0113909,10913844,1212729,2016-03-24T04:00:00+00:00,2022-01-01T04:59:59+00:00,
ak1,Default Organization,,,,Default Organization View,"",Yes,,,Employee SKU,Red Hat,1,ES0113909,10913844,1212729,2016-03-24T04:00:00+00:00,2022-01-01T04:59:59+00:00,akofink-desktop.usersys.redhat.com
```

**Comment by thomasmckay** [comment]
@akofink - found and fixed the problem, please retest

**Comment by akofink** [comment]
@thomasmckay Very nice messages now for subs on an activation key :+1:

Unfortunately, I'm still getting an issue in this scenario:

```sh
$ hammer csv activation-keys --itemized-subscriptions --export --file aksi.csv -v
$ cat aksi.csv 
Name,Organization,Description,Limit,Environment,Content View,Host Collections,Auto-Attach,Service Level,Release Version,Subscription Name,Subscription Type,Subscription Quantity,Subscription SKU,Subscription Contract,Subscription Account,Subscription Start,Subscription End,Subscription Guest
ak1,Default Organization,,,,Default Organization View,"",Yes,,,Employee SKU,Red Hat,1,ES0113909,10913844,1212729,2016-03-24T04:00:00+00:00,2022-01-01T04:59:59+00:00,
ak1,Default Organization,,,,Default Organization View,"",Yes,,,Employee SKU,Red Hat Guest,1,ES0113909,10913844,1212729,2016-03-24T04:00:00+00:00,2022-01-01T04:59:59+00:00,akofink-desktop.usersys.redhat.com
ak2,Default Organization,,,,cv4,"",Yes,,,Employee SKU,Red Hat,1,ES0113909,10913844,1212729,2016-03-24T04:00:00+00:00,2022-01-01T04:59:59+00:00,
ak2,Default Organization,,,,cv4,"",Yes,,,Employee SKU,Red Hat Guest,1,ES0113909,10913844,1212729,2016-03-24T04:00:00+00:00,2022-01-01T04:59:59+00:00,akofink-desktop.usersys.redhat.com
$ # Delete all subs on ak2
$ hammer csv activation-keys --itemized-subscriptions --file aksi.csv -v
Updating subscriptions for activation key 'ak1'... 'Employee SKU' already attached...done
Updating subscriptions for activation key 'ak1'... 'Employee SKU - Guest of akofink-desktop.usersys.redhat.com' already attached...done
Updating subscriptions for activation key 'ak2'... attaching 1 of 'Employee SKU'...done
Updating subscriptions for activation key 'ak2'...Error: No matching subscriptions
ak2,Default Organization,,,,cv4,"",Yes,,,Employee SKU,Red Hat Guest,1,ES0113909,10913844,1212729,2016-03-24T04:00:00+00:00,2022-01-01T04:59:59+00:00,akofink-desktop.usersys.redhat.com
```

I can reattach the guest subscription through the UI, however.

**Comment by akofink** [comment]
Here's my content host, rhel1 (who knows if it makes sense to have these subs like this):

image

Here's an export and re-import, without deleting any subs from the host:

```sh
$ hammer csv content-hosts --organization 'Default Organization' --itemized-subscriptions --file hostsubs.csv -v --export

$ hammer csv content-hosts --organization 'Default Organization' --itemized-subscriptions --file hostsubs.csv -v
Updating subscriptions for content host 'akofink-desktop.usersys.redhat.com'... 'Employee SKU' already attached...done
Updating subscriptions for content host 'rhel1.example.com'... 'Employee SKU - Guest of akofink-desktop.usersys.redhat.com' already attached...done
Updating subscriptions for content host 'rhel1.example.com'... 'Employee SKU - Guest of akofink-desktop.usersys.redhat.com' already attached...done

$ cat hostsubs.csv 
Name,Organization,Environment,Content View,Host Collections,Virtual,Guest of Host,OS,Arch,Sockets,RAM,Cores,SLA,Products,Subscription Name,Subscription Type,Subscription Quantity,Subscription SKU,Subscription Contract,Subscription Account,Subscription Start,Subscription End,Subscription Guest
akofink-desktop.usersys.redhat.com,Default Organization,Library,Default Organization View,"",No,,Fedora 25,x86_64,1,32936388,4,"","",Employee SKU,Red Hat,1,ES0113909,10913844,1212729,03/24/2016,01/01/2022,
rhel1.example.com,Default Organization,Library,cv4,"",Yes,akofink-desktop.usersys.redhat.com,Red Hat Enterprise Linux Server 7.2,x86_64,2,1883984,1,"",69|Red Hat Enterprise Linux Server,Employee SKU,Red Hat Guest,1,ES0113909,10913844,1212729,03/24/2016,01/01/2022,akofink-desktop.usersys.redhat.com
rhel1.example.com,Default Organization,Library,cv4,"",Yes,akofink-desktop.usersys.redhat.com,Red Hat Enterprise Linux Server 7.2,x86_64,2,1883984,1,"",69|Red Hat Enterprise Linux Server,Employee SKU,Red Hat Guest,1,ES0113909,10913844,1212729,03/24/2016,01/01/2022,akofink-desktop.usersys.redhat.com
```

**Comment by thomasmckay** [comment]
@akofink : alright, this is it! ... i hope! i wasn't clearing the column values between sub export. i left the commit there for you to see the diff easily.

**Comment by akofink** [comment]
@thomasmckay I hate to say it but...

Same setup as before, where rhel1 host has both physical and guest subs of 'Employee SKU'. The message is incorrect when the subs are already attached to the rhel1 host, and the subscription is not found at all when trying to attach the two subs to the rhel1 host.

```sh
$ cat hostsubs.csv 
Name,Organization,Environment,Content View,Host Collections,Virtual,Guest of Host,OS,Arch,Sockets,RAM,Cores,SLA,Products,Subscription Name,Subscription Type,Subscription Quantity,Subscription SKU,Subscription Contract,Subscription Account,Subscription Start,Subscription End,Subscription Guest
akofink-desktop.usersys.redhat.com,Default Organization,Library,Default Organization View,"",No,,Fedora 25,x86_64,1,32936388,4,"","",Employee SKU,Red Hat,1,ES0113909,10913844,1212729,03/24/2016,01/01/2022,
rhel1.example.com,Default Organization,Library,cv4,"",Yes,akofink-desktop.usersys.redhat.com,Red Hat Enterprise Linux Server 7.2,x86_64,2,1883984,1,"",69|Red Hat Enterprise Linux Server,Employee SKU,Red Hat,1,ES0113909,10913844,1212729,03/24/2016,01/01/2022,
rhel1.example.com,Default Organization,Library,cv4,"",Yes,akofink-desktop.usersys.redhat.com,Red Hat Enterprise Linux Server 7.2,x86_64,2,1883984,1,"",69|Red Hat Enterprise Linux Server,Employee SKU,Red Hat Guest,1,ES0113909,10913844,1212729,03/24/2016,01/01/2022,akofink-desktop.usersys.redhat.com
```

Trying to attach when rhel1 host has no subs:

```sh
$ hammer csv content-hosts --organization 'Default Organization' --itemized-subscriptions --file hostsubs.csv -v
Updating subscriptions for content host 'akofink-desktop.usersys.redhat.com'... 'Employee SKU' already attached...done
Updating subscriptions for content host 'rhel1.example.com'...Error: No matching subscriptions
rhel1.example.com,Default Organization,Library,cv4,"",Yes,akofink-desktop.usersys.redhat.com,Red Hat Enterprise Linux Server 7.2,x86_64,2,1883984,1,"",69|Red Hat Enterprise Linux Server,Employee SKU,Red Hat,1,ES0113909,10913844,1212729,03/24/2016,01/01/2022,
```

Already attached:

```sh
$ hammer csv content-hosts --organization 'Default Organization' --itemized-subscriptions --file hostsubs.csv -v
Updating subscriptions for content host 'akofink-desktop.usersys.redhat.com'... 'Employee SKU' already attached...done
Updating subscriptions for content host 'rhel1.example.com'... 'Employee SKU - Guest of akofink-desktop.usersys.redhat.com' already attached...done
Updating subscriptions for content host 'rhel1.example.com'... 'Employee SKU - Guest of akofink-desktop.usersys.redhat.com' already attached...done
```

It looks like the "Virtual" column is getting filled in when it should have an empty string (perhaps?).

**Pull request merged**
