### PR TITLE
Fixes #15748 - Test on Ruby 2.1-2.2

### PR DESCRIPTION
**Pull request by akofink**
Let's see if the tests pass! :game_die:

### CODE REVIEW

**Comment by thomasmckay** [comment]
[test]

**Comment by thomasmckay** [comment]
APJ

**Comment by thomasmckay** [comment]
[test]

**Comment by akofink** [comment]
This build failure on Ruby 2.0 is the same as https://github.com/theforeman/hammer-cli/pull/198

**Pull request merged**
