### PR TITLE
fixes #16428 - set domain FastGettext

### PR DESCRIPTION
**Pull request by thomasmckay**
Initialize FastGettext properly for calling other modules

### CODE REVIEW

**Comment by thomasmckay** [comment]
http://www.rubydoc.info/gems/grosser-fast_gettext/0.4.2

This seems to be the correct fix for this if threads are involved, which hammer-cli-csv supports.

**Comment by thomasmckay** [comment]
[test]

**Comment by thomasmckay** [comment]
[test]

**Comment by thomasmckay** [comment]
[test]

**Comment by beav** [comment]
ack, seems reasonable

**Pull request merged**
