### PR TITLE
fixes #15743 - import and export of subscriptions one-per-line

### PR DESCRIPTION
**Pull request by thomasmckay**

### CODE REVIEW

**Comment by thomasmckay** [comment]
[test]

**Comment by beav** [comment]
I'm not able to make per-line comments for some reason. Two comments:

* please add a note to http://projects.theforeman.org/issues/16234 with a link to where the TODO is, so whoever fixes it remembers to remove the workaround

* the block at ` lib/hammer_cli_csv/base.rb` line 77 might be rewritten to be more verbose in its test conditions for readability. Maybe something like:

```ruby
# apologies for whitespace issues
      if option_export? && option_file
          CSV.open(option_file, 'wb', {:force_quotes => false}) do |csv|
            export csv
          end
      elsif option_export? && !option_file
         CSV do |csv|
            export csv
         end
      elsif !option_export
        import
      end
```

Overall the patch looks good though.

**Comment by thomasmckay** [comment]
Note added to issue.

The code block I'd prefer to keep the same for now, with an "export" block and an "import" block. I think this will be clearer if at some point more options are added. At that point I'd probably suggest breaking the if/else into their own separate methods. If I combine into if/elsif/else now I think future would just slap in another elsif (the refactor wouldn't be as obvious). @beav you alright with that?

**Comment by beav** [comment]
@thomasmckay ya that works for me

**Pull request merged**
