### PR TITLE
[WIP] Fixes #17052 - Handle virt_only subs on an AK

### PR DESCRIPTION
**Pull request by akofink**
WIP for tests

### CODE REVIEW

**Comment by thomasmckay** [comment]
I was thinking that the solution would be more along the lines of what content-hosts has, where we would add a 'Host' (ie. hypervisor) column. This would then be used as one of the factors in narrowing down the subscriptions here https://github.com/Katello/hammer-cli-csv/blob/master/lib/hammer_cli_csv/content_hosts.rb#L316-L320 . In this way, a subscription for "VDC guests of hv1" could be added w/ sub name of "VDC" and Host column value of "hv1". This would make the utils/subscriptions.rb applicable to both content-hosts and activation-keys (I'm refactoring that code section there to fix http://theforeman.org/issues/17505 ).

**Comment by akofink** [comment]
@thomasmckay That sounds fine with me. I know the CSV output so far in this project is easy to edit by users, and that informs the format of the columns. Not being as familiar, I went with a more direct approach here, but I'm totally willing to favor a more human-editable approach.

**Comment by thomasmckay** [comment]
@akofink - Alright, let me poke at this topic today and see if the refactor will work.

**Comment by thomasmckay** [comment]
@akofink https://github.com/Katello/hammer-cli-csv/pull/142

**Pull request closed without merging**
